/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RevendaRouteImport } from './routes/revenda'
import { Route as InstrucoesRouteImport } from './routes/instrucoes'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminThemeRouteImport } from './routes/admin.theme'
import { Route as AdminResellersRouteImport } from './routes/admin.resellers'
import { Route as AdminPlansRouteImport } from './routes/admin.plans'
import { Route as AdminIptvRouteImport } from './routes/admin.iptv'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminClientsRouteImport } from './routes/admin.clients'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'
import { Route as AdminAutomationRouteImport } from './routes/admin.automation'
import { Route as AcessoTokenRouteImport } from './routes/acesso.$token'
import { Route as ApiPublicMercadopagoRouteImport } from './routes/api.public.mercadopago'

const RevendaRoute = RevendaRouteImport.update({
  id: '/revenda',
  path: '/revenda',
  getParentRoute: () => rootRouteImport,
} as any)
const InstrucoesRoute = InstrucoesRouteImport.update({
  id: '/instrucoes',
  path: '/instrucoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminThemeRoute = AdminThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResellersRoute = AdminResellersRouteImport.update({
  id: '/resellers',
  path: '/resellers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIptvRoute = AdminIptvRouteImport.update({
  id: '/iptv',
  path: '/iptv',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAutomationRoute = AdminAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AdminRoute,
} as any)
const AcessoTokenRoute = AcessoTokenRouteImport.update({
  id: '/acesso/$token',
  path: '/acesso/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMercadopagoRoute = ApiPublicMercadopagoRouteImport.update({
  id: '/api/public/mercadopago',
  path: '/api/public/mercadopago',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/instrucoes': typeof InstrucoesRoute
  '/revenda': typeof RevendaRoute
  '/acesso/$token': typeof AcessoTokenRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/iptv': typeof AdminIptvRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/instrucoes': typeof InstrucoesRoute
  '/revenda': typeof RevendaRoute
  '/acesso/$token': typeof AcessoTokenRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/iptv': typeof AdminIptvRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin': typeof AdminIndexRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/instrucoes': typeof InstrucoesRoute
  '/revenda': typeof RevendaRoute
  '/acesso/$token': typeof AcessoTokenRoute
  '/admin/automation': typeof AdminAutomationRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/iptv': typeof AdminIptvRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/resellers': typeof AdminResellersRoute
  '/admin/theme': typeof AdminThemeRoute
  '/admin/': typeof AdminIndexRoute
  '/api/public/mercadopago': typeof ApiPublicMercadopagoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/instrucoes'
    | '/revenda'
    | '/acesso/$token'
    | '/admin/automation'
    | '/admin/calendar'
    | '/admin/clients'
    | '/admin/finance'
    | '/admin/iptv'
    | '/admin/plans'
    | '/admin/resellers'
    | '/admin/theme'
    | '/admin/'
    | '/api/public/mercadopago'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/instrucoes'
    | '/revenda'
    | '/acesso/$token'
    | '/admin/automation'
    | '/admin/calendar'
    | '/admin/clients'
    | '/admin/finance'
    | '/admin/iptv'
    | '/admin/plans'
    | '/admin/resellers'
    | '/admin/theme'
    | '/admin'
    | '/api/public/mercadopago'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/instrucoes'
    | '/revenda'
    | '/acesso/$token'
    | '/admin/automation'
    | '/admin/calendar'
    | '/admin/clients'
    | '/admin/finance'
    | '/admin/iptv'
    | '/admin/plans'
    | '/admin/resellers'
    | '/admin/theme'
    | '/admin/'
    | '/api/public/mercadopago'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  InstrucoesRoute: typeof InstrucoesRoute
  RevendaRoute: typeof RevendaRoute
  AcessoTokenRoute: typeof AcessoTokenRoute
  ApiPublicMercadopagoRoute: typeof ApiPublicMercadopagoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/revenda': {
      id: '/revenda'
      path: '/revenda'
      fullPath: '/revenda'
      preLoaderRoute: typeof RevendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/instrucoes': {
      id: '/instrucoes'
      path: '/instrucoes'
      fullPath: '/instrucoes'
      preLoaderRoute: typeof InstrucoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/theme': {
      id: '/admin/theme'
      path: '/theme'
      fullPath: '/admin/theme'
      preLoaderRoute: typeof AdminThemeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resellers': {
      id: '/admin/resellers'
      path: '/resellers'
      fullPath: '/admin/resellers'
      preLoaderRoute: typeof AdminResellersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/iptv': {
      id: '/admin/iptv'
      path: '/iptv'
      fullPath: '/admin/iptv'
      preLoaderRoute: typeof AdminIptvRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/automation': {
      id: '/admin/automation'
      path: '/automation'
      fullPath: '/admin/automation'
      preLoaderRoute: typeof AdminAutomationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/acesso/$token': {
      id: '/acesso/$token'
      path: '/acesso/$token'
      fullPath: '/acesso/$token'
      preLoaderRoute: typeof AcessoTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/mercadopago': {
      id: '/api/public/mercadopago'
      path: '/api/public/mercadopago'
      fullPath: '/api/public/mercadopago'
      preLoaderRoute: typeof ApiPublicMercadopagoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAutomationRoute: typeof AdminAutomationRoute
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminIptvRoute: typeof AdminIptvRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminResellersRoute: typeof AdminResellersRoute
  AdminThemeRoute: typeof AdminThemeRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAutomationRoute: AdminAutomationRoute,
  AdminCalendarRoute: AdminCalendarRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminIptvRoute: AdminIptvRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminResellersRoute: AdminResellersRoute,
  AdminThemeRoute: AdminThemeRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  InstrucoesRoute: InstrucoesRoute,
  RevendaRoute: RevendaRoute,
  AcessoTokenRoute: AcessoTokenRoute,
  ApiPublicMercadopagoRoute: ApiPublicMercadopagoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
